### ISSUE TITLE
gzipping files after conversion

### ISSUE THREAD

**Issue by stolarczyk** [databio/bed_maker#10]
the bedfiles which are result of a conversion from other formats are not gzipped. To make the bedmaker output consistent, they should be gzipped after the conversion.

**Comment by joseverdezoto** [comment]
@stolarczyk   if we have `wig, bw, bigBed, bedGraph` files in `gzip` format and we want to gunzip them to perform the conversion, I'm debating what to do with the `gzip` and newly unzipped files. I think that it'd better to keep the `gzip` files and delete the unzipped files once the conversion is done. Thoughts?

**Comment by stolarczyk** [comment]
Yes, I’d remove just the byproducts, so we end up with an original file and gzipped bed every single time

**Comment by joseverdezoto** [comment]
Ok that's what I imagined. I made some changes so that any files that are unzipped for conversion are later removed. I also wrote a bit of code to gzip the new `bed` files and keep only that file format. I haven't yet figured out a way to check for `gzip` format integrity, other than grabbing the file name extension.  Might need to revisit the gzip library documentation or use the gzip magic number `1f 8b`  :pensive:

**Comment by stolarczyk** [comment]
> I haven't yet figured out a way to check for gzip format integrity

If you refer to the input bed file here, you can `try` compressing it with `gzip.GzipFile()`. If the file is not compressed I'll just do it (which is desirable in this case). Otherwise `OSError` is raised, which you can catch and just continue.

**Comment by stolarczyk** [comment]
>  I haven't yet figured out a way to check for gzip format integrity, other than grabbing the file name extension

I think, that's good for now
